package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Clase que describe el objeto dispositivo con sus setters y getters
 * Dispositivo generated by hbm2java
 */
public class Dispositivo  implements java.io.Serializable {

     private Long codigo;
     private TipoDispositivo tipoDispositivo;
     private String descripcion;
     private String estado;
     private Set prestamos = new HashSet(0);

/**
      * Constructor vacio
      */
    public Dispositivo() {
    }
/**
	 * Constructor del objeto Dispositivo con todos sus atributos
	 * @param tipoDispositivo parametro que describe el tipo de dispositivo
	 * @param descripcion un texto que describe el dispositivo y otros extras que tiene el dispositivo
	 * @param estado describe el estado en el que se encuentra el dispositivo (prestado, en mantenimiento, etc)
	 */
	
    public Dispositivo(TipoDispositivo tipoDispositivo, String descripcion, String estado) {
        this.tipoDispositivo = tipoDispositivo;
        this.descripcion = descripcion;
        this.estado = estado;
    }

 /**
     * 
     * @param tipoDispositivo
     * @param descripcion
     * @param estado
     * @param prestamos
     */

    public Dispositivo(TipoDispositivo tipoDispositivo, String descripcion, String estado, Set prestamos) {
       this.tipoDispositivo = tipoDispositivo;
       this.descripcion = descripcion;
       this.estado = estado;
       this.prestamos = prestamos;
    }
    /**
    * Getter
    * @return codigo del dispositivo
    */
    public Long getCodigo() {
        return this.codigo;
    }
    /**
     * Setter
     * @param codigo el codigo de la materia
     */
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    /**
     * Getter
     * @return el tipo de dispositivo
     */
    public TipoDispositivo getTipoDispositivo() {
        return this.tipoDispositivo;
    }

/**
     * Setter
     * @param tipoDispositivo es el tipo dispositivo a asignar
     */
    
    public void setTipoDispositivo(TipoDispositivo tipoDispositivo) {
        this.tipoDispositivo = tipoDispositivo;
    }

/**
     * Getter
     * @return una cadena de caracteres con la descripcion del dispositivo
     */

    public String getDescripcion() {
        return this.descripcion;
    }
    
/**
     * Setter
     * @param descripcion asigna un descripcion a un dispositivo
     */

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

/**
     * Getter
     * @return el estado de un dispositivo
     */
    public String getEstado() {
        return this.estado;
    }
    
  /**
     * Setter
     * @param estado asigna un estado a un dispositivo
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

/**
     * Getter
     * @return una lista de todos los prestamos que se realizaron del dispositivo 
     */
    public Set getPrestamos() {
        return this.prestamos;
    }
    /**
     * Asigna una lista de los prestamos realizados al dispositivo
     * @param prestamos la lista que se le asigna a un dispositivo
     */
    public void setPrestamos(Set prestamos) {
        this.prestamos = prestamos;
    }




}


