package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0


/**
 * Clase que modela el objeto Usuario
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private UsuarioId id;
     private TipoUsuario tipoUsuario;
     private String nombres;
     private String apellidos;
     private String correo;
     private String estado;
     private String password;

     /**
      * Constructor vacio
      */
    public Usuario() {
    }
    /**
     * Constructor con todos los parametros
     * @param id Identificacion del usuario
     * @param tipoUsuario al que pertenece el usuario
     * @param nombres del usuario
     * @param apellidos del usuario
     * @param correo del usuario
     * @param estado si se encuentra activo o penalizado
     */
    public Usuario(UsuarioId id, TipoUsuario tipoUsuario, String nombres, String apellidos, String correo, String estado) {
       this.id = id;
       this.tipoUsuario = tipoUsuario;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.correo = correo;
       this.estado = estado;
    }

     /**
     * Getter
     * @return el identificador del usuario
     */
    public UsuarioId getId() {
        return this.id;
    }
    
    
    /**
     * Setter
     * @param id del usuario que lo identifica
     */
    public void setId(UsuarioId id) {
        this.id = id;
    }
    
    /**
     * Getter
     * @return el tipo usuario al que pertenece
     */
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
        
    /**
     * Setter
     * @param tipoUsuario al que pertenece el usuario
     */
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    
    /**
     * Getter
     * @return el o los nombres del usuario
     */
    public String getNombres() {
        return this.nombres;
    }
        
    /**
     * Setter
     * @param nombres que se le asignan al usuario
     */
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    /**
     * Getter
     * @return los apellidos del usuario
     */
    public String getApellidos() {
        return this.apellidos;
    }
        /**
     * Setter
     * @param apellidos que se asignan al usuario
     */
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    /**
     * Getter
     * @return el correo del usuario
     */
    public String getCorreo() {
        return this.correo;
    }
        
    /**
     * Setter
     * @param correo que se asigna al usuario
     */
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    
    /**
     * Getter
     * @return el estado del usuario
     */
    public String getEstado() {
        return this.estado;
    }
        
    /**
     * Setter
     * @param estado que se asigna al usuario
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * Getter
     * @return el password del usuario
     */
	public String getPassword() {
		return password;
	}

	/**
	 * Setter
	 * @param password que se asigna al usuario
	 */
	public void setPassword(String password) {
		this.password = password;
	}

}


