package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * Clase que modela el objeto tipo de dispositivo
 * TipoDispositivo generated by hbm2java
 */
public class TipoDispositivo  implements java.io.Serializable {


     private Integer codigo;
     private String tipo;
     @JsonIgnore
     private Set dispositivos = new HashSet(0);

     /**
      * Constructor vacio
      */
    public TipoDispositivo() {
    }

	/**
	 * Constructor solo con un parametro
	 * @param tipo es el tipo de dispositivo
	 */
	
    public TipoDispositivo(String tipo) {
        this.tipo = tipo;
    }
    
    /**
     * Constructor con todos los parametros
     * @param tipo es el tipo de dispositivo
     * @param dispositivos son los dispositivos que son del mismo tipo
     */
    public TipoDispositivo(String tipo, Set dispositivos) {
       this.tipo = tipo;
       this.dispositivos = dispositivos;
    }

   /**
     * Getter
     * @return el codigo del tipo de dispositivo
     */
    public Integer getCodigo() {
        return this.codigo;
    }
        
    /**
     * Setter
     * @param codigo que se asigna al tipo de dispositivo
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
   
    /**
     * Getter
     * @return el tipo del dispositivo 
     */
    public String getTipo() {
        return this.tipo;
    }
    
    /**
     * Setter
     * @param tipo que se asigna al dispositivo
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * Getter
     * @return los dispositivos que pertenecen al tipo
     */
    public Set getDispositivos() {
        return this.dispositivos;
    }
    
    /**
     * Setter
     * @param dispositivos que pertenecen al tipo
     */
    public void setDispositivos(Set dispositivos) {
        this.dispositivos = dispositivos;
    }




}


