package com.prestamos.dto;
// Generated 17/07/2014 03:01:05 PM by Hibernate Tools 3.6.0


/**
 * Clase que modela el objeto UsuarioId
 * UsuarioId generated by hbm2java
 */
public class UsuarioId  implements java.io.Serializable {

/**
 * Parametros
 */

     private String tipoDocumento;
     private String numeroDocumento;

     /**
      * Constructor vacio
      */
    public UsuarioId() {
    }

    /**
     * Constructor con todos los parametros
     * @param tipoDocumento es el tipo de documento del usuario
     * @param numeroDocumento es el numero de documento del usuario
     */
    public UsuarioId(String tipoDocumento, String numeroDocumento) {
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
    }
      
    /**
     * Getter
     * @return el tipo del documento del usuarioId
     */
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
        
    /**
     * Setter
     * @param tipoDocumento del usuario
     */
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    
    /**
     * Getter
     * @return el numero de documento del usuario
     */
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
        
    /**
     * Setter
     * @param numeroDocumento del usuario
     */
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }


    /**
     * metodo que compara si 2 usuarioIds son iguales
     * @param other el otro usuario id con el cual se compara
     * @return un booleano, true si son igual, false si son diferentes
     */
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioId) ) return false;
		 UsuarioId castOther = ( UsuarioId ) other; 
         
		 return ( (this.getTipoDocumento()==castOther.getTipoDocumento()) || ( this.getTipoDocumento()!=null && castOther.getTipoDocumento()!=null && this.getTipoDocumento().equals(castOther.getTipoDocumento()) ) )
 && ( (this.getNumeroDocumento()==castOther.getNumeroDocumento()) || ( this.getNumeroDocumento()!=null && castOther.getNumeroDocumento()!=null && this.getNumeroDocumento().equals(castOther.getNumeroDocumento()) ) );
   }
      
   /**
    * Metodo que genera un codigo hash para el usuarioId
    * @return el codigo hash del usuarioId
    */
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTipoDocumento() == null ? 0 : this.getTipoDocumento().hashCode() );
         result = 37 * result + ( getNumeroDocumento() == null ? 0 : this.getNumeroDocumento().hashCode() );
         return result;
   }   


}


